### ISSUE TITLE
Accept Intergers in the constuctor

### ISSUE THREAD

**Issue by wanderer** [cryptocoinjs/bigi#18]
It would be nice if you could initialize bigi with an intereger like so

``` javascript
var bi = require('bigi'); 
var aNumber = bi(9);
```

Currently if you try this you get

```
typeError: Cannot call method 'nextBytes' of undefined
    at BigInteger.bnpFromNumber [as fromNumber] (/home/null/code/bigi/lib/bigi.js:775:7)
    at new BigInteger (/home/null/code/bigi/lib/bigi.js:7:36)
    at BigInteger (/home/null/code/bigi/lib/bigi.js:4:12)

```

**Comment by dcousens** [comment]
Closing in in favour of https://github.com/cryptocoinjs/bigi/pull/27
